"""AI Tools module."""

from app.ai.tools.analytics_tools import (
    calculate_kpi_tool,
    revenue_analytics_tool,
    sales_analytics_tool,
)
from app.ai.tools.dashboard_tools import (
    get_dashboard_summary_tool,
    get_dashboard_tool,
)
from app.ai.tools.ml_tools import (
    predict_tool,
    run_forecast_tool,
)
from app.ai.tools.registry import ToolDefinition, ToolRegistry
from app.ai.tools.report_tools import (
    generate_executive_summary_tool,
    generate_report_tool,
)
from app.ai.tools.schemas import (
    ChartRequest,
    ChartResponse,
    ChatRequest,
    ChatResponse,
    Citation,
    CitationResponse,
    ForecastRequest,
    ForecastResponse,
    GenerateReportRequest,
    GenerateReportResponse,
    GetDashboardRequest,
    GetDashboardResponse,
    GetDashboardSummaryRequest,
    GetDashboardSummaryResponse,
    IntentDetection,
    KPICalculateRequest,
    KPICalculateResponse,
    NLQQuery,
    RecommendationRequest,
    RecommendationResponse,
    RevenueAnalyticsRequest,
    RevenueAnalyticsResponse,
    RootCauseAnalysisRequest,
    RootCauseAnalysisResponse,
    SalesAnalyticsRequest,
    SalesAnalyticsResponse,
)

__all__ = [
    "ChartRequest",
    "ChartResponse",
    "ChatRequest",
    "ChatResponse",
    "Citation",
    "CitationResponse",
    "ForecastRequest",
    "ForecastResponse",
    "GenerateReportRequest",
    "GenerateReportResponse",
    "GetDashboardRequest",
    "GetDashboardResponse",
    "GetDashboardSummaryRequest",
    "GetDashboardSummaryResponse",
    "IntentDetection",
    "KPICalculateRequest",
    "KPICalculateResponse",
    "NLQQuery",
    "RecommendationRequest",
    "RecommendationResponse",
    "RevenueAnalyticsRequest",
    "RevenueAnalyticsResponse",
    "RootCauseAnalysisRequest",
    "RootCauseAnalysisResponse",
    "SalesAnalyticsRequest",
    "SalesAnalyticsResponse",
    "ToolDefinition",
    "ToolRegistry",
    "calculate_kpi_tool",
    "generate_executive_summary_tool",
    "generate_report_tool",
    "get_dashboard_summary_tool",
    "get_dashboard_tool",
    "predict_tool",
    "revenue_analytics_tool",
    "run_forecast_tool",
    "sales_analytics_tool",
]
