apiVersion: v1
kind: Namespace
metadata:
  name: bi-platform
  labels:
    app.kubernetes.io/part-of: bi-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: bi-platform-monitoring
  labels:
    app.kubernetes.io/part-of: bi-platform
